version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kulachipo
      POSTGRES_PASSWORD: kulachipo_pass
      POSTGRES_DB: kulachipo_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 